### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by benwilson512** [radar/chronic#1]
I saw you ask for code review the other day, thought I would share some pointers.
- `@doc` on the public API functions would be handy
- Stuff like https://github.com/radar/chronic/blob/master/lib/chronic.ex#L61 could just be `def date_for({date, _}), do: date` There’s a lot of cases like that where it may make sense to pattern match in the function head instead of on the first line of the function
- Be careful with pattern matching on keyword lists because they’re order dependent. Maps are not. I think it might make the most sense to use a map or struct for your year month day stuff.
- In general it’s best to try to avoid meta-programming in complex logic https://github.com/radar/chronic/blob/master/lib/chronic/processors/plain_time.ex. If you’re going to do so have the functions inside `quote do` simply call to functions in the ordinary module body. This is becaues it can be hard to debug code inside a macro. The contents are injected into the other module which means that it’s all one line number.

I do see why you’re going with that approach, so that you can pattern match on the word

There’s a lot of good stuff, sorry for the deluge of pointers :)

**Comment by radar** [comment]
Thanks @benwilson512. I really appreciate it :)

I think using pattern matching for the `process` funcs make sense, but for `combine` it doesn't seem to make as much sense. I might take a look at refactoring that later.

Based on your advice and others from #elixir-lang, I've moved the logic from the other modules back into `Chronic`. I did that mainly so that when an exception was raised I would get some proper file / line number info out of it.

Thank you very much for taking the time look over my codebase.
